absoluteurl: http://pearsonca.github.io
baseurl: /stdio-ghana
markdown: kramdown
markdown_ext: md
activeClass: class="active"
highlighter: pygments
encoding: utf-8
navPages:
 - instructors
 - sessions
 - reports
 - projects
 - schedule
 - misc
exclude:
 - run.sh
 - INSTALL.md
 - README.md
collections:
  instructors:
    output: true
